name: Sync Fork

on:
  schedule:
    - cron: '0 4 * * *'  # Daily at 04:00 UTC
  workflow_dispatch: # Allow manual invocation

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/DancinDinoo/awesome-lists.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories || true
          git push origin main
